"""
DynamicViT + PyTorch Padded baseline.

Same DeiT-Small backbone, but the keep-mask is generated by the
DynamicViT Prediction Module (an active MLP router) instead of
simple L2-norm thresholding.

The "Mask Generation Overhead" from the prediction module is included
in the measured latency — this is the honest cost of an active router.
After pruning, tokens are gathered + zero-padded back to [B, S, D]
exactly like the A-ViT padded baseline.
"""

import torch
import torch.nn as nn

from models.deit_base import load_deit, split_deit, get_dtype
from models.dynamicvit_gate import DynamicViTPredictionModule
from models.pruning import pytorch_gather_and_pad
from baselines.pytorch_pruned import PaddedBlock
from config import DEVICE, EMBED_DIM


def build_dynamicvit_pytorch_model():
    """
    Returns a model with DynamicViT gate + PyTorch padded execution.
    Callable as model(images, fixed_ratio=0.5).
    """
    deit = load_deit()
    front, early, late_seq, back = split_deit(deit)
    late_blocks = nn.ModuleList([PaddedBlock(b) for b in late_seq])
    gate = DynamicViTPredictionModule(embed_dim=EMBED_DIM)

    class DynamicViTPaddedDeiT(nn.Module):
        def __init__(self):
            super().__init__()
            self.front = front
            self.early = early
            self.gate = gate
            self.late_blocks = late_blocks
            self.back = back

        @torch.inference_mode()
        def forward(self, images, fixed_ratio=None):
            x = self.front(images)        # [B, 197, 384]
            x = self.early(x)             # [B, 197, 384]

            # ── DynamicViT gate (active router) ──────────────────
            mask = self.gate(x, fixed_ratio=fixed_ratio)       # [B, 197] bool

            # ── gather + pad (PyTorch way) ───────────────────────
            x_pad, attn_mask_bool, num_kept = pytorch_gather_and_pad(x, mask)

            B, S, D = x_pad.shape
            attn_mask = torch.zeros(B, 1, 1, S, device=x.device, dtype=x.dtype)
            attn_mask.masked_fill_(
                ~attn_mask_bool.unsqueeze(1).unsqueeze(2), float("-inf")
            )

            # ── late layers with mask ────────────────────────────
            for block in self.late_blocks:
                x_pad = block(x_pad, attn_mask=attn_mask)

            return self.back(x_pad)

    model = DynamicViTPaddedDeiT().to(DEVICE, dtype=get_dtype()).eval()
    return model
