"""
DynamicViT + Triton Ragged pipeline.

Same DeiT-Small backbone, but the keep-mask is generated by the
DynamicViT Prediction Module (active MLP router).  After masking,
tokens are packed into a flat [Total_Kept, D] tensor via our Triton
packer and processed with zero-padding ragged attention.

This demonstrates the "checkmate" argument:
  Even with the heavier DynamicViT gate overhead, the Triton engine
  recovers the time by eliminating all padding waste.
"""

import torch
import torch.nn as nn

from models.deit_base import load_deit, split_deit, get_dtype
from models.dynamicvit_gate import DynamicViTPredictionModule
from models.triton_ragged_deit import RaggedAttentionBlock
from kernels.pack_tokens import triton_pack_tokens
from config import DEVICE, EMBED_DIM


class DynamicViTRaggedDeiT(nn.Module):
    """
    front → early blocks → DynamicViT gate → Triton pack → ragged late blocks → classify
    """

    def __init__(self, front, early, late_blocks_list, back, gate):
        super().__init__()
        self.front = front
        self.early = early
        self.gate = gate
        self.ragged_blocks = nn.ModuleList(
            [RaggedAttentionBlock(b) for b in late_blocks_list]
        )
        self.back_norm = back.norm
        self.back_head = back.head

    @torch.inference_mode()
    def forward(self, images: torch.Tensor, fixed_ratio: float | None = None):
        B = images.shape[0]

        x = self.front(images)       # [B, 197, 384]
        x = self.early(x)            # [B, 197, 384]

        # ── DynamicViT gate (active router) ──────────────────────
        mask = self.gate(x, fixed_ratio=fixed_ratio)       # [B, 197] bool

        # ── Triton pack ──────────────────────────────────────────
        packed, cu_seqlens = triton_pack_tokens(x, mask)   # [T, 384], [B+1]

        # ── ragged transformer layers ────────────────────────────
        for block in self.ragged_blocks:
            packed = block(packed, cu_seqlens)

        # ── extract CLS tokens ───────────────────────────────────
        cls_indices = cu_seqlens[:-1].long()               # [B]
        cls_tokens = packed[cls_indices]                    # [B, 384]

        cls_tokens = self.back_norm(cls_tokens)
        logits = self.back_head(cls_tokens)
        return logits


def build_dynamicvit_triton_model():
    """Returns a DynamicViTRaggedDeiT ready for inference."""
    deit = load_deit()
    front, early, late_seq, back = split_deit(deit)
    late_blocks_list = list(late_seq)
    gate = DynamicViTPredictionModule(embed_dim=EMBED_DIM)

    model = DynamicViTRaggedDeiT(front, early, late_blocks_list, back, gate)
    model = model.to(DEVICE, dtype=get_dtype()).eval()
    return model
